PumpMyPump/Models/SportEquip.cs
using PumpMyPump.Models.MetaDatas;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PumpMyPump.Models
{
    [MetadataType(typeof(SportEquipMetaData))]
    public partial class SportEquip
    {
    }
}

PumpMyPump/Controllers/SportEquipController.cs
using PumpMyPump.App_Code;
using PumpMyPump.Helpers;
using PumpMyPump.Models;
using PumpMyPump.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PumpMyPump.Controllers
{
    public class SportEquipController : BaseAuthController
    {
        private DbDataContext db = DataBase.Connect;

        public ActionResult Index(string sortBy = "name", bool isAsc = true)
        {
            IEnumerable<SportEquip> sportEquips = db.CurrentSportEquips;

            #region Sorting
            switch (sortBy)
            {
                default:
                    sportEquips = isAsc ? sportEquips.OrderBy(p => p.Name) : sportEquips.OrderByDescending(p => p.Name);
                    break;
            }
            #endregion

            ViewBag.SortBy = sortBy;
            ViewBag.IsAsc = isAsc;

            return View(sportEquips.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SportEquip sportEquip = db.SportEquips.FirstOrDefault(bp => bp.Id == id);
            if (sportEquip == null)
            {
                return HttpNotFound();
            }
            return View(sportEquip);
        }

        public ActionResult Create()
        {
            var viewSportEquip = new ViewSportEquip();
            return View(viewSportEquip);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewSportEquip viewSportEquip)
        {
            var fileName = RenameUploadPhoto(viewSportEquip.Photo);

            if (ModelState.IsValid)
            {
                var user = AuthHelper.User;
                var sportEquip = new SportEquip
                {
                    Name = viewSportEquip.Name,
                    Photo = fileName,
                    UserId = user.IsAdmin ? 0 : user.Id
                };

                db.SportEquips.InsertOnSubmit(sportEquip);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }

            return View(viewSportEquip);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var sportEquip = db.SportEquips.FirstOrDefault(bp => bp.Id == id);
            if (sportEquip == null)
            {
                return HttpNotFound();
            }

            var viewSportEquip = new ViewSportEquip
            {
                Name = sportEquip.Name,
                PhotoName = sportEquip.Photo
            };

            return View(viewSportEquip);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ViewSportEquip viewSportEquip)
        {
            var fileName = "";
            if (viewSportEquip.Photo != null)
            {
                fileName = RenameUploadPhoto(viewSportEquip.Photo);
            }

            if (ModelState.IsValid)
            {
                var dbSportEquip = db.SportEquips.FirstOrDefault(bp => bp.Id == viewSportEquip.Id);

                dbSportEquip.Name = viewSportEquip.Name;
                if (fileName.Length != 0)
                {
                    dbSportEquip.Photo = fileName;
                }

                db.SubmitChanges();
                return RedirectToAction("Index");
            }

            return View(viewSportEquip);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var sportEquip = db.SportEquips.FirstOrDefault(bp => bp.Id == id);

            if (sportEquip == null)
            {
                return HttpNotFound();
            }

            return View(sportEquip);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var sportEquip = db.SportEquips.FirstOrDefault(bp => bp.Id == id);
            db.SportEquips.DeleteOnSubmit(sportEquip);
            db.SubmitChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string RenameUploadPhoto(HttpPostedFileBase photo)
        {
            var fileName = "";
            if (photo == null)
            {
                fileName = "/images/no_photo.png";
            }
            else
            {
                var iu = new ImageUpload(128, 128, "sportequip");
                var result = iu.RenameUploadFile(photo);

                if (result.Success)
                {
                    fileName = result.ImageName;
                }
                else
                {
                    ModelState.AddModelError("Photo", result.ErrorMessage);
                }
            }

            return fileName;
        }
    }
}

PumpMyPump/Views/SportEquip/Create.cshtml
@model PumpMyPump.Models.ViewModels.ViewSportEquip

@{
    ViewBag.Title = "Добавить снаряд";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить</h2>
@using (Html.BeginForm("Create", "SportEquip", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_Form", Model)
}

PumpMyPump/Views/SportEquip/Edit.cshtml
@model PumpMyPump.Models.ViewModels.ViewSportEquip

@{
    ViewBag.Title = "Изменить снаряд";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
@using (Html.BeginForm("Edit", "SportEquip", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_Form", Model)
}

PumpMyPump/Views/SportEquip/Index.cshtml
@using PumpMyPump.Helpers
@model IEnumerable<PumpMyPump.Models.SportEquip>

@{
    ViewBag.Title = "Снаряды";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var user = AuthHelper.User;
}

<h2>Снаряды</h2>
<table class="table">
    <tr>
        <th class="col-md-2">
            Фото
        </th>
        <th class="col-md-8">
            @SortHelper.Link("SportEquip", "Название", "name", ViewBag.SortBy, ViewBag.IsAsc)
        </th>
        <th class="col-md-2">
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="col-md-2">
                <img src="@item.Photo" alt="@item.Name" class="img-thumbnail">
            </td>
            <td class="col-md-8">
                <a href="@Url.Action("Edit", new { id = item.Id })">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </td>
            <td class="col-md-2">
                @if (user.IsAdmin || (user.IsUser && @item.UserId == user.Id))
                {
                    using (Html.BeginForm("Delete", "SportEquip", new { id = item.Id }))
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" class="btn btn-sm btn-danger">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    }
                }
            </td>
        </tr>
    }
</table>
@if (Model.Count() == 0)
{
    <h3>Список пуст.</h3>
}
<div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Create")" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Добавить
        </a>
    </div>
</div>

PumpMyPump/Views/SportEquip/_Form.cshtml
@model PumpMyPump.Models.ViewModels.ViewSportEquip

@Html.AntiForgeryToken()
@Html.HiddenFor(model => model.Id)

<div class="form-horizontal">
    <img src="@Model.PhotoName" alt="@Model.Name" class="img-thumbnail">
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label for="@Model.Photo" class="col-sm-2 control-label">Фото:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Photo, new { type = "file" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Name" class="col-sm-2 control-label">Название:</label>
        <div class="col-md-6">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-8">
            <input type="submit" value="@(Model.Id == 0 ? "Добавить" : "Сохранить")" class="btn btn-success" />
        </div>
    </div>
</div>