PumpMyPump/Models/Exercise.cs
using PumpMyPump.Models.MetaDatas;
using PumpMyPump.Models.Types;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PumpMyPump.Models
{
    [MetadataType(typeof(ExerciseMetaData))]
    public partial class Exercise
    {
        public ScoreType ScoreType
        {
            get { return ScoreType.GetList().FirstOrDefault(s => s.Value == Score); }
        }

        public LevelType LevelType
        {
            get { return LevelType.GetList().FirstOrDefault(s => s.Value == Level); }
        }

        public HttpPostedFileBase PhotoFile { get; set; }

        public string BodyPartName { get; set; }

        public string SportEquipName { get;  set; }

        public string MuscleName { get; set; }
    }
}

PumpMyPump/Controllers/ExerciseController.cs
using PumpMyPump.App_Code;
using PumpMyPump.Helpers;
using PumpMyPump.Models;
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PumpMyPump.Controllers
{
    public class ExerciseController : BaseAuthController
    {
        private DbDataContext db = DataBase.Connect;

        public ActionResult Index(string sortBy = "name", bool isAsc = true, string searchName = "", int searchLevel = -1, int searchScore = -1)
        {
            DataLoadOptions loadOptions = new DataLoadOptions();
            loadOptions.LoadWith<Exercise>(e => e.BodyPart);
            loadOptions.LoadWith<Exercise>(e => e.Muscle);
            loadOptions.LoadWith<Exercise>(e => e.SportEquip);
            db.LoadOptions = loadOptions;

            IEnumerable<Exercise> exercises = db.CurrentExercises;

            #region Sorting
            switch (sortBy)
            {
                case "level":
                    exercises = isAsc ? exercises.OrderBy(p => p.Level) : exercises.OrderByDescending(p => p.Level);
                    break;

                case "score":
                    exercises = isAsc ? exercises.OrderBy(p => p.Score) : exercises.OrderByDescending(p => p.Score);
                    break;

                default:
                    exercises = isAsc ? exercises.OrderBy(p => p.Name) : exercises.OrderByDescending(p => p.Name);
                    break;
            }
            #endregion

            searchName = searchName.Trim();
            if (searchName.Length != 0)
            {
                exercises = exercises.Where(t => t.Name.ToLower().Contains(searchName));
            }

            if (searchLevel != -1)
            {
                exercises = exercises.Where(t => t.Level == searchLevel);
            }

            if (searchScore != -1)
            {
                exercises = exercises.Where(t => t.Score == searchScore);
            }

            ViewBag.SortBy = sortBy;
            ViewBag.IsAsc = isAsc;

            var re = new List<Exercise>();
            if (exercises.Count() != 0)
            {
                re = exercises.ToList();
            }

            return View(re);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Exercise exercise = db.Exercises.FirstOrDefault(bp => bp.Id == id);
            if (exercise == null)
            {
                return HttpNotFound();
            }

            return View(exercise);
        }

        public ActionResult Create()
        {
            var exercise = new Exercise();

            return View(exercise);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Exercise exercise)
        {
            var fileName = RenameUploadPhoto(exercise.PhotoFile);

            if (ModelState.IsValid)
            {
                var user = AuthHelper.User;
                exercise.UserId = user.IsAdmin ? 0 : user.Id;

                exercise.Photo = fileName;
                db.Exercises.InsertOnSubmit(exercise);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }

            return View(exercise);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Exercise exercise = db.Exercises.FirstOrDefault(bp => bp.Id == id);
            if (exercise == null)
            {
                return HttpNotFound();
            }

            return View(exercise);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Exercise exercise)
        {
            var fileName = "";
            if (exercise.PhotoFile != null)
            {
                fileName = RenameUploadPhoto(exercise.PhotoFile);
            }

            if (ModelState.IsValid)
            {
                Exercise dbExercise = db.Exercises.FirstOrDefault(bp => bp.Id == exercise.Id);
                dbExercise.BodyPartId = exercise.BodyPartId;
                dbExercise.MuscleId = exercise.MuscleId;
                dbExercise.SportEquipId = exercise.SportEquipId;
                dbExercise.Name = exercise.Name;
                dbExercise.Description = exercise.Description;
                dbExercise.Video = exercise.Video;
                dbExercise.Sets = exercise.Sets;
                dbExercise.Reps = exercise.Reps;
                dbExercise.Level = exercise.Level;
                dbExercise.Score = exercise.Score;

                if (fileName.Length != 0)
                {
                    dbExercise.Photo = fileName;
                }

                db.SubmitChanges();
                return RedirectToAction("Index");
            }

            return View(exercise);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Exercise exercise = db.Exercises.FirstOrDefault(bp => bp.Id == id);

            if (exercise == null)
            {
                return HttpNotFound();
            }

            return View(exercise);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exercise exercise = db.Exercises.FirstOrDefault(bp => bp.Id == id);
            db.Exercises.DeleteOnSubmit(exercise);
            db.SubmitChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private string RenameUploadPhoto(HttpPostedFileBase photo)
        {
            var fileName = "";
            if (photo == null)
            {
                fileName = "/images/no_photo.png";
            }
            else
            {
                var iu = new ImageUpload(128, 128, "exercise");
                var result = iu.RenameUploadFile(photo);

                if (result.Success)
                {
                    fileName = result.ImageName;
                }
                else
                {
                    ModelState.AddModelError("Photo", result.ErrorMessage);
                }
            }

            return fileName;
        }
    }
}

PumpMyPump/Views/Exercise/Create.cshtml
@model PumpMyPump.Models.Exercise

@{
    ViewBag.Title = "Добавить упражнение";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить</h2>
@using (Html.BeginForm("Create", "Exercise", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.Partial("_Form", Model)
}

@section scripts
{
    @Html.Partial("_FormScript")
}

PumpMyPump/Views/Exercise/Details.cshtml
@model PumpMyPump.Models.Exercise
@{
    ViewBag.Title = "Просмотр упражнения";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<img src="@Model.Photo" alt="@Model.Name" class="img-thumbnail">
<hr />

<div class="form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label">Часть тела:</label>
        <span class="col-sm-8 control-label text-left">@Model.BodyPart.Name</span>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Мышца:</label>
        <span class="col-sm-8 control-label text-left">@Model.Muscle.Name</span>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Снаряд:</label>
        <span class="col-sm-8 control-label text-left">@Model.SportEquip.Name</span>
    </div>

    @if (@Model.Video != null)
    {
        <div class="form-group">
            <label class="col-sm-2 control-label">Видео:</label>
            <iframe width="560" height="315" src="@Model.Video.Replace(".com/", ".com/embed/").Replace("watch?v=", "")  " frameborder="0" allowfullscreen></iframe>
        </div>
    }

    <div class="form-group">
        <label class="col-sm-2 control-label">Подходы:</label>
        <span class="col-sm-8 control-label text-left">@Model.Sets</span>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Повторения:</label>
        <span class="col-sm-8 control-label text-left">@Model.Reps</span>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Цель:</label>
        <span class="col-sm-8 control-label text-left">@Model.ScoreType.Name</span>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Уровень:</label>
        <span class="col-sm-8 control-label text-left">@Model.LevelType.Name</span>
    </div>

    @if (@Model.Description != null)
    {
        <div class="form-group">
            <label class="col-sm-2 control-label">Описание:</label>
            <span class="col-sm-8 control-label text-left">@Html.Raw(Model.Description.Replace(" ", "&nbsp;").Replace("\r\n", "<br />"))</span>
        </div>
    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-6">
            <a href="@Url.Action("Index")" class="btn btn-default">
                Назад
            </a>
        </div>
    </div>
</div>

PumpMyPump/Views/Exercise/Edit.cshtml
@model PumpMyPump.Models.Exercise

@{
    ViewBag.Title = "Изменить упражнение";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
@using (Html.BeginForm("Edit", "Exercise", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_Form", Model)
}

@section scripts
{
    @Html.Partial("_FormScript")
}

PumpMyPump/Views/Exercise/Index.cshtml
@using PumpMyPump.Helpers
@model IEnumerable<PumpMyPump.Models.Exercise>

@{
    ViewBag.Title = "Упражнения";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var user = AuthHelper.User;
    string search = ViewBag.SearchName;
    IEnumerable<SelectListItem> ScoreList = PumpMyPump.Helpers.AppHelper.ScoreListAll;
    IEnumerable<SelectListItem> LevelList = PumpMyPump.Helpers.AppHelper.LevelListAll;
}
<h2>Упражнения</h2>

<form action="@Url.Action("Index")" method="get">
    <div class="row">
        <div class="col-md-4">
            @Html.Hidden("sortBy")
            @Html.Hidden("isAsc")
            @Html.TextBox("SearchName", search, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.DropDownList("SearchLevel", LevelList, new { @class = "selectpicker", @data_live_search = "true" })
        </div>
        <div class="col-md-3">
            @Html.DropDownList("SearchScore", ScoreList, new { @class = "selectpicker", @data_live_search = "true" })
        </div>
        <div class="col-md-2">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-btn-info">
                    Поиск
                </button>
                <a href="@Url.Action("Index")" class="btn btn-default">
                    Сброс
                </a>
            </div>
        </div>
    </div>
    <table class="table">
        <tr>
            <th class="col-md-2">
                @SortHelper.Link("Exercise", "Название", "name", ViewBag.SortBy, ViewBag.IsAsc)
            </th>
            <th class="col-md-1">
                @SortHelper.Link("Exercise", "Уровень", "level", ViewBag.SortBy, ViewBag.IsAsc)
            </th>
            <th class="col-md-1">
                @SortHelper.Link("Exercise", "Цель", "score", ViewBag.SortBy, ViewBag.IsAsc)
            </th>
            <th class="col-md-2">
                Часть тела
            </th>
            <th class="col-md-2">
                Мышца
            </th>
            <th class="col-md-2">
                Снаряд
            </th>
            <th class="col-md-2">
            </th>
        </tr>
    </table>
</form>
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td class="col-md-2">
                @if (user.IsAdmin || (user.IsUser && @item.UserId == user.Id))
                {
                    <a href="@Url.Action("Edit", new { id = item.Id })">
                        @item.Name
                    </a>
                }
            </td>
            <td class="col-md-1">
                @item.LevelType.Name
            </td>
            <td class="col-md-1">
                @item.ScoreType.Name
            </td>
            <td class="col-md-2">
                @item.BodyPart.Name
            </td>
            <td class="col-md-2">
                @item.Muscle.Name
            </td>
            <td class="col-md-2">
                @item.SportEquip.Name
            </td>
            <td class="col-md-2">
                @if (user.IsAdmin || (user.IsUser && @item.UserId == user.Id))
                {
                    using (Html.BeginForm("Delete", "Exercise", new { id = item.Id }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-sm btn-info">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a>
                        <button type="submit" class="btn btn-sm btn-danger">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    }
                }
                else
                {
                    <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-sm btn-info">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                }
            </td>
        </tr>
    }
</table>
@if (Model.Count() == 0)
{
    <h3>Список пуст.</h3>
}
<div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Create")" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Добавить
        </a>
    </div>
</div>

PumpMyPump/Views/Exercise/_Form.cshtml
@model PumpMyPump.Models.Exercise

@Html.AntiForgeryToken()
@Html.HiddenFor(model => model.Id)

@{
    IEnumerable<SelectListItem> BodyPartList = PumpMyPump.Helpers.AppHelper.BodyPartList;
    IEnumerable<SelectListItem> MuscleList = PumpMyPump.Helpers.AppHelper.MuscleList;
    IEnumerable<SelectListItem> SportEquipList = PumpMyPump.Helpers.AppHelper.SportEquipList;
    IEnumerable<SelectListItem> ScoreList = PumpMyPump.Helpers.AppHelper.ScoreList;
    IEnumerable<SelectListItem> LevelList = PumpMyPump.Helpers.AppHelper.LevelList;
}


<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label for="@Model.BodyPartId" class="col-sm-2 control-label">Часть тела:</label>
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.BodyPartId, BodyPartList, new { @class = "selectpicker", @data_live_search = "true" })
            @Html.ValidationMessageFor(m => m.BodyPartId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.MuscleId" class="col-sm-2 control-label">Мышца:</label>
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.MuscleId, MuscleList, new { @class = "selectpicker", @data_live_search = "true" })
            @Html.ValidationMessageFor(m => m.MuscleId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.SportEquipId" class="col-sm-2 control-label">Снаряд:</label>
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.SportEquipId, SportEquipList, new { @class = "selectpicker", @data_live_search = "true" })
            @Html.ValidationMessageFor(m => m.SportEquipId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.PhotoFile" class="col-sm-2 control-label">Фото:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.PhotoFile, new { type = "file" })
            @Html.ValidationMessageFor(m => m.PhotoFile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Video" class="col-sm-2 control-label">Видео:</label>
        <div class="col-md-6">
            @Html.TextBoxFor(model => model.Video, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Name" class="col-sm-2 control-label">Название:</label>
        <div class="col-md-6">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Sets" class="col-sm-2 control-label">Подходы:</label>
        <div class="col-md-3">
            @Html.TextBoxFor(model => model.Sets, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sets, "", new { @class = "text-danger" })
        </div>
        <label for="@Model.Reps" class="col-sm-2 control-label">Повторения:</label>
        <div class="col-md-3">
            @Html.TextBoxFor(model => model.Reps, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Reps, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Score" class="col-sm-2 control-label">Цель:</label>
        <div class="col-md-3">
            @Html.DropDownListFor(m => m.Score, ScoreList, new { @class = "selectpicker", @data_live_search = "true" })
            @Html.ValidationMessageFor(m => m.Score, "", new { @class = "text-danger" })
        </div>
        <label for="@Model.Level" class="col-sm-2 control-label">Уровень:</label>
        <div class="col-md-3">
            @Html.DropDownListFor(m => m.Level, LevelList, new { @class = "selectpicker", @data_live_search = "true" })
            @Html.ValidationMessageFor(m => m.Level, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="@Model.Description" class="col-sm-2 control-label">Описание:</label>
        <div class="col-md-8">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-8">
            <input type="submit" value="@(Model.Id == 0 ? "Добавить" : "Сохранить")" class="btn btn-success" />
            <a href="@Url.Action("Index")" class="btn btn-default">
                Назад
            </a>
        </div>
    </div>
</div>

PumpMyPump/Views/Exercise/_FormScript.cshtml
<script type="text/javascript">
    $('.selectpicker').selectpicker({
        style: 'btn-white',
        size: 7
    });
</script>