PumpMyPump/Controllers/SignInController.cs
using PumpMyPump.App_Code;
using PumpMyPump.Helpers;
using PumpMyPump.Models;
using PumpMyPump.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PumpMyPump.Controllers
{
    public class SignInController : Controller
    {
        private DbDataContext db = DataBase.Connect;

        public ActionResult Index()
        {
            var regUser = new SignInUser();

            return View(regUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SignInUser signInUser)
        {
            if (AuthHelper.UserExists(signInUser.Email))
            {
                ModelState.AddModelError("Email", "Такой пользователь уже есть в системе.");
            }

            if (ModelState.IsValid)
            {
                var user = new User
                {
                    Email = signInUser.Email,
                    Password = AuthHelper.Crypt(signInUser.Password),
                    Weight = signInUser.Weight,
                    Length = signInUser.Length,
                    ArmSize = 9,
                    Level = signInUser.Level,
                    Score = signInUser.Score,
                    Role = 1,
                };

                db.Users.InsertOnSubmit(user);
                db.SubmitChanges();

                AuthHelper.Login(user.Email, signInUser.Password);
                return RedirectToAction("Index", "Home");
            }

            return View("Index", signInUser);
        }
    }
}

PumpMyPump/Views/SignIn/Index.cshtml
@model PumpMyPump.Models.ViewModels.SignInUser

@{
    ViewBag.Title = "Регистрация";
    Layout = "~/Views/Shared/_Layout.cshtml";

    IEnumerable<SelectListItem> RoleList = PumpMyPump.Helpers.AppHelper.RoleList;
    IEnumerable<SelectListItem> ScoreList = PumpMyPump.Helpers.AppHelper.ScoreList;
    IEnumerable<SelectListItem> LevelList = PumpMyPump.Helpers.AppHelper.LevelList;
}

<h2>Регистрация</h2>
@using (Html.BeginForm("Create", "SignIn"))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="@Model.Email" class="col-sm-2 control-label">Email:</label>
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="@Model.Password" class="col-sm-2 control-label">Пароль:</label>
            <div class="col-md-6">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="@Model.Level" class="col-sm-2 control-label">Уровень:</label>
            <div class="col-md-2">
                @Html.DropDownListFor(m => m.Level, LevelList, new { @class = "selectpicker" })
                @Html.ValidationMessageFor(m => m.Level, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="@Model.Length" class="col-sm-2 control-label">Рост см:</label>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.Length, new { @class = "form-control length" })
                @Html.ValidationMessageFor(m => m.Length, "", new { @class = "text-danger" })
            </div>
            <label for="@Model.Weight" class="col-sm-2 control-label">Вес кг:</label>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.Weight, new { @class = "form-control weight" })
                @Html.ValidationMessageFor(m => m.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Результат:</label>
            <div class="col-md-2">
                <input class="form-control result" readonly>
            </div>
            <label for="@Model.Score" class="col-sm-2 control-label">Цель:</label>
            <div class="col-md-2">
                @Html.DropDownListFor(m => m.Score, ScoreList, new { @class = "selectpicker" })
                @Html.ValidationMessageFor(m => m.Score, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="@(Model.Id == 0 ? "Добавить" : "Сохранить")" class="btn btn-success" />
                <a href="@Url.Action("Index")" class="btn btn-default">
                    Назад
                </a>
            </div>
        </div>
    </div>
}

@section scripts
{
    <script type="text/javascript">
        function calculateIndex() {
            var length = parseInt($(".length").first().val());
            var weight = parseInt($(".weight").first().val());

            length = Math.max(length, 1);
            weight = Math.max(weight, 1);

            var index = weight / ((length / 100) * (length / 100));
            $(".result").val(indexResult(index));
        }

        function indexResult(index) {
            if (index > 25) {
                return "Избыточный вес";
            }

            if (index > 18.5) {
                return "Норма";
            }

            return "Недостаток массы";
        }

        $(".length").change(function () {
            calculateIndex();
        });

        $(".weight").change(function () {
            calculateIndex();
        });

        calculateIndex();
    </script>
}