PumpMyPump/Controllers/LogInController.cs
using PumpMyPump.App_Code;
using PumpMyPump.Helpers;
using PumpMyPump.Models;
using PumpMyPump.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PumpMyPump.Controllers
{
    public class LogInController : Controller
    {
        private DbDataContext db = DataBase.Connect;

        public ActionResult Index()
        {
            var loginUser = new LoginUser();

            return View(loginUser);
        }

        public ActionResult Logout()
        {
            AuthHelper.Logout();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LoginUser loginUser)
        {
            if (ModelState.IsValid)
            {
                if (AuthHelper.Login(loginUser.Email, loginUser.Password))
                {
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("Email", "Пара логин и пароль не совпадают.");
            }

            return View("Index", loginUser);
        }
    }
}

PumpMyPump/Views/LogIn/Index.cshtml
@model PumpMyPump.Models.ViewModels.LoginUser

@{
    ViewBag.Title = "Авторизация";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Авторизация</h2>
@using (Html.BeginForm("Create", "LogIn"))
{
    @Html.AntiForgeryToken()
    <hr />

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="@Model.Email" class="col-sm-2 control-label">Email:</label>
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="@Model.Password" class="col-sm-2 control-label">Пароль:</label>
            <div class="col-md-6">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Авторизация" class="btn btn-success" />
                <a href="@Url.Action("Index", "Home")" class="btn btn-default">
                    Назад
                </a>
            </div>
        </div>
    </div>
}